### ISSUE TITLE
Request adding readable() usage examples in README

### ISSUE THREAD

**Issue by 2264381489** [hsbijarniya/data_format#2]
Hello, I'm a new Dart learner who just started picking up DateTime formatting using the readable() method. I have some confusions and would like to kindly ask for your advice:

I did not find example codes of readable() in the README doc. As a beginner, example codes would really help me better understand the usage of this method. I wonder if it's possible to add some examples?
When trying it myself, using "yy" to format year did not produce the result I expected:

```dart
DateTime date = DateTime(2023, 2, 28);

String format1 = date.readable('year'); 
// except:2023
// actual:2023

String format2 = date.readable('yy');
// except:23
// actual:yy

String format3 = date.readable('year,yy');
// except:23
// actual:2023,yy
```
I think some example codes would greatly help me and other new learners better grasp the usage of readable().

Therefore, if convenient, could I kindly ask if you could add some readable() call examples in the README, including but not limited to:

Examples of formatting date/time using yy, year etc.
Examples combining different format specifiers
Examples showing the running results
Of course these are just my personal thoughts. Please feel free to provide other good suggestions if you have any.

I sincerely appreciate you taking the time to read my issue. Your guidance would mean a lot to me as a beginner. Thank you!

**Comment by hsbijarniya** [comment]
updated

**Comment by 2264381489** [comment]
thanks
